name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  go:
    uses: poseidon/.github/.github/workflows/golang-library.yaml@main
  multiarch:
    #uses: poseidon/fleetlock/.github/workflows/multiarch.yaml@main
    uses: ./.github/workflows/multiarch.yaml
    secrets:
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
